<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Simon Kiss, Wilfrid Laurier University">
<meta name="author" content="Rafael Campos-Gottardo, McGill University">

<title>NOC Coding</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Merge_Diagnose_Execute_files/libs/clipboard/clipboard.min.js"></script>
<script src="Merge_Diagnose_Execute_files/libs/quarto-html/quarto.js"></script>
<script src="Merge_Diagnose_Execute_files/libs/quarto-html/popper.min.js"></script>
<script src="Merge_Diagnose_Execute_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Merge_Diagnose_Execute_files/libs/quarto-html/anchor.min.js"></script>
<link href="Merge_Diagnose_Execute_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Merge_Diagnose_Execute_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Merge_Diagnose_Execute_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Merge_Diagnose_Execute_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Merge_Diagnose_Execute_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import">Data Import</a></li>
  <li><a href="#diagnostics" id="toc-diagnostics" class="nav-link" data-scroll-target="#diagnostics">Diagnostics</a></li>
  <li><a href="#merge-with-each-file" id="toc-merge-with-each-file" class="nav-link" data-scroll-target="#merge-with-each-file">Merge With Each File</a>
  <ul class="collapse">
  <li><a href="#ces2019-phone" id="toc-ces2019-phone" class="nav-link" data-scroll-target="#ces2019-phone">CES2019 Phone</a></li>
  <li><a href="#ces19-web" id="toc-ces19-web" class="nav-link" data-scroll-target="#ces19-web">CES19 Web</a></li>
  <li><a href="#ces21-web" id="toc-ces21-web" class="nav-link" data-scroll-target="#ces21-web">CES21 Web</a></li>
  </ul></li>
  <li><a href="#comprehensive-diagnostics" id="toc-comprehensive-diagnostics" class="nav-link" data-scroll-target="#comprehensive-diagnostics">Comprehensive Diagnostics</a></li>
  <li><a href="#export-of-data-files" id="toc-export-of-data-files" class="nav-link" data-scroll-target="#export-of-data-files">Export of data files</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">NOC Coding</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Simon Kiss, Wilfrid Laurier University </p>
             <p>Rafael Campos-Gottardo, McGill University </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The purpose of this document is to document how we merged unique job titles drawn from the CES19 phone, CES19 web and CES21 surveys, coded with codes from Canada’s National Occupation Classification and to provide some diagnostics of the coding and merging. We undertook this at the request of the Consortium on Electoral Democracy.</p>
<p>While the initial request was only to code the occupation responses for the CES21 dataset, we included the 2019 surveys for two reasons. First, the CES19 surveys are closer in time to the Government of Canada’s 2021 National Occupation Classification than the 2016 NOC and, second, because of repeat entries, it was anticipated that this would not necessarily add a lot of extra work. That is to say, there are only so many ways respondents can enter the job title “nurse”, “teacher”, “carpenter”, etc.</p>
</section>
<section id="data-import" class="level2">
<h2 class="anchored" data-anchor-id="data-import">Data Import</h2>
<p>First, we imported the three files containing respondents and converted each variable containing occupation and job titles into all lower-case strings. Then we filtered only unique responses. As a result, <code>Teacher</code> and <code>teacher</code> became a single entry, but spelling mistakes were kept. So, we were left with a spreadsheet containing responses such as <code>teacher</code> and <code>teahcher</code>, and, more specific entries such as <code>elementary teacher</code>. This variable alone was exported into an Excel spreadsheet for coding by two research assistants.</p>
<p>Second, we imported the Excel spreadsheet that contains the unique occupation titles contained in the three surveys and the 4-digit and 5-digit NOC codes assigned by coders. More can and will be said about what the difference between the 4- and 5-digit codes, but basically it is simply that the 5-digit codes are more specific. This is an innovation in the NOC that emerged between 2016 and 2021.</p>
<p>As an example, someone providing the response “Kindergarden Teacher” could be classed with the 5-digit NOC code 41221 - “Elementary School and Kindergarten Teachers”. However, someone providing the response “Teacher” could be plausibly be an elementary or a secondary school teacher. The latter has the 5-digit code 41220. But both share the 4-digit code 4122.</p>
<p>But, presumably, researchers could make use of the information in the 4-digit code. As a result, after initially coding each response with a 5-digit code, we re-coded remaining responses with a 4-digit code and then copied the the first 4-digits of the 5-digit codes assigned to those in the first attempt.</p>
<p>As a result, the file with the NOC codes contains the unique, lower-case responses from the three survey files, a 5-digit NOC codes for <em>some</em> of the responses that were specific enough, and 4-digit NOC codes for those responses <em>plus</em> other responses that were somewhat more vague, but specific enough to assign to a 4-digit code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_excel</span>(<span class="at">path=</span><span class="fu">here</span>(<span class="st">"Data/occupations_coded.xlsx"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Select only the columns with the unique job title and the NOC codes</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"title"</span>, <span class="st">"NOC21_4"</span>, <span class="st">"NOC21_5"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Set 0s to be missing in the two columns containing the NOC code</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="fu">across</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="cf">function</span>(x) car<span class="sc">::</span><span class="fu">Recode</span>(x, <span class="st">"0=NA"</span>, <span class="at">as.numeric=</span>T)))<span class="ot">-&gt;</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Store as object noc</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  noc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics">Diagnostics</h2>
<p>First we check to see the maximum number of characters in the 4-digit and 5-digit NOC variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is a check</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>noc <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Convert each NOC variable to character, then count the characters in each entry</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="fu">across</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="sc">~</span><span class="fu">nchar</span>(<span class="fu">as.character</span>(.)))) <span class="sc">%&gt;%</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#check that each has a maximum of 4 and 5 respectively</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="sc">~</span><span class="fu">max</span>(., <span class="at">na.rm=</span>T)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  NOC21_4 NOC21_5
    &lt;int&gt;   &lt;int&gt;
1       4       5</code></pre>
</div>
</div>
<p>Second, we show some basic statistics about the NOC codes assigned.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  skim_variable n_missing valid pct_complete
  &lt;chr&gt;             &lt;int&gt; &lt;int&gt;        &lt;dbl&gt;
1 NOC21_4            1262  6642        0.840
2 NOC21_5            1691  6213        0.786</code></pre>
</div>
</div>
<p>There were 7904 unique responses to the questions soliciting job titles in the CES19 Phone, CES19 Web and CES21 Web. Of these, we were able to match 6213 NOC 5-digit codes and 6642 4-digit codes.</p>
<p>There are several reasons for why we cannot assign an NOC code to each job title.</p>
<ol type="1">
<li><p>Many responses were broader than NOC codes permit. For example, some responses have more to do with a person’s economic sector or organizational function than their job title. Many respondents might respond “human resources” or “IT” which are hard to assign to an NOC code because it lacks skill level and task information. Other respondents provided something like “self-employed” which is not an occupation.</p></li>
<li><p>In the web surveys, respondents who did not report they worked were given the opportunity to record their job title, leading to many responses such as “on medical leave” or “retired police officer”. Note, that the survey flow in the 2019 Phone survey was different; respondents were only asked their occupation if they previously answered that they had any paid employment. In the interests of consistency, <em>we have not assigned any NOC codes to any responses where it is clear the respondent was not working (e.g.&nbsp;“retired teacher”, “cashier on sick leave”).</em> Users interested in these variables should consider the possibility that there is still useful information that can be gleaned from searches of the open-ended text responses which we have refrained from coding into the NOC to avoid pre-judging other users’ responses.</p></li>
</ol>
</section>
<section id="merge-with-each-file" class="level2">
<h2 class="anchored" data-anchor-id="merge-with-each-file">Merge With Each File</h2>
<p>The next step is to merge back the lower-case, unique job titles <em>back</em> into each CES file. We do this in the following way.</p>
<section id="ces2019-phone" class="level3">
<h3 class="anchored" data-anchor-id="ces2019-phone">CES2019 Phone</h3>
<p>First we import the 2019 CES phone survey.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ces19phone<span class="ot">&lt;-</span><span class="fu">read_dta</span>(<span class="fu">here</span>(<span class="at">file=</span><span class="st">"Data/2019 Canadian Election Study - Phone Survey v1.0.dta"</span>),<span class="at">encoding=</span><span class="st">"utf-8"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We convert the occupation variable to lower case and merge with the <code>noc</code> dataset using the <code>title</code> variable in the <code>noc</code> dataset and the <code>p52_lower</code> variable in the <code>ces19phone</code> dataset as the key variables. So, this is taking any respondent in <code>ces19phone</code> who provided a job title and adding an NOC21-5 and NOC21-4 variable to that job title from the <code>noc</code> spreadsheet we created.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Convert p52 to lower case</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p52_lower=</span><span class="fu">str_to_lower</span>(p52)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#merge with noc keying on p52_lower and title</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(., noc, <span class="at">by=</span><span class="fu">join_by</span>(<span class="st">"p52_lower"</span><span class="sc">==</span><span class="st">"title"</span>))<span class="ot">-&gt;</span>ces19phone</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="diagnostics-2019-phone" class="level4">
<h4 class="anchored" data-anchor-id="diagnostics-2019-phone">Diagnostics 2019 Phone</h4>
<p>In the following, we run some basic diagnostic tests to see how the merge funtioned. First, we wanted to see how the survey flow functioned in each survey, specifically, whether people who responded they were not technically employed actually had the opportunity to provide responses. So, first we converted the employment status variable into something useful. Specifically, we coded the employment status variable into a 3-category variable where respondents were either <code>employed</code>, <code>retired</code> or <code>other</code>. We will mirror this for the other surveys as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">employment=</span><span class="fu">case_when</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">#If Q68 is between 0 and 4 employed</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    q68<span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> q68<span class="sc">&lt;</span> <span class="dv">4</span><span class="sc">~</span> <span class="st">"Employed"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If Q68 is between 8 and 12 employed</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    q68<span class="sc">&gt;</span> <span class="dv">8</span> <span class="sc">&amp;</span>q68<span class="sc">&lt;</span><span class="dv">12</span><span class="sc">~</span> <span class="st">"Employed"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">#If Q68 is 4 set Retired</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    q68<span class="sc">==</span><span class="dv">4</span><span class="sc">~</span> <span class="st">"Retired"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">#All other responses (e.g. student, family caregiver, don't know )</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Set to other</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span> </span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Set the factor levels for the new employment variable</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">employment=</span><span class="fu">factor</span>(employment, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Employed"</span>, <span class="st">"Retired"</span>, <span class="st">"Other"</span>)))<span class="ot">-&gt;</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Save back into ces19phone</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  ces19phone</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Show results </span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ces19phone<span class="sc">$</span>employment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Employed  Retired    Other 
    2638      971      412 </code></pre>
</div>
</div>
<p>Then we report the valid and missing NOC codes for respondents in the 2019 CES Phone dataset by employment status.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(employment, <span class="fu">contains</span>(<span class="st">"NOC"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(employment) <span class="sc">%&gt;%</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">my_skim</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(employment, skim_variable, n_missing<span class="sc">:</span>pct_complete) <span class="sc">%&gt;%</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(employment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  employment skim_variable n_missing valid pct_complete
  &lt;fct&gt;      &lt;chr&gt;             &lt;int&gt; &lt;int&gt;        &lt;dbl&gt;
1 Employed   NOC21_4            1171  1467        0.556
2 Employed   NOC21_5            1349  1289        0.489
3 Retired    NOC21_4             971     0        0    
4 Retired    NOC21_5             971     0        0    
5 Other      NOC21_4             412     0        0    
6 Other      NOC21_5             412     0        0    </code></pre>
</div>
</div>
<p>Here we can see the survey flow was explicit: only people who responded they were employed were given the opportunity to respond with an occupation title and so they have no responses for the NOC21-4 and NOC21-5 variables.</p>
<p>We can show the results of the NOC coding here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(p52_lower, NOC21_4, NOC21_5) <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#This filters to include only those who responded with the following options</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(., <span class="fu">str_detect</span>(p52_lower, <span class="st">"carpenter|plumber|camionneur|infirmière|electricien|enseignant|menuisier|plombier|driver|nurse|doctor|teacher|electrician"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 3
   p52_lower                                           NOC21_4 NOC21_5
   &lt;chr&gt;                                                 &lt;dbl&gt;   &lt;dbl&gt;
 1 business man, truck driver, farmer                     7330   73300
 2 taxi driver, full time and english tutor, part-time    7520   75200
 3 teacher                                                4122      NA
 4 enseignante secondaire                                 4122   41220
 5 registered nurse                                       3130   31301
 6 fuel truck driver                                      7330   73300
 7 carpenter                                              7231   72310
 8 teacher                                                4122      NA
 9 infirmière                                             3130   31301
10 truck driver                                           7330   73300
11 semi retired teacher                                   4122      NA
12 teacher                                                4122      NA
13 frunace oil delivery driver                            7330   73300
14 long distance truck driver                             7330   73300
15 enseignante                                            4122      NA
16 enseignante au primaire                                4122   41221
17 carpenter's apprentice                                 7231   72310
18 zomboni driver, shift duty engineer                    6521   65211
19 medical doctor                                         3110   31102
20 student teacher                                        4310   43100
21 carpenter                                              7231   72310
22 school bus driver                                      7330   73301
23 teacher                                                4122      NA
24 electrician                                            7220   72200
25 camionneur courte distance, locale                     7330   73300
26 driver                                                 7520   75200
27 teacher                                                4122      NA
28 carpenter                                              7231   72310
29 teacher - elementary and secondary                     4122      NA
30 registered nurse                                       3130   31301
31 nurse rn                                               3130   31301
32 carpenter                                              7231   72310
33 electrician                                            7220   72200
34 enseignante                                            4122      NA
35 infirmière                                             3130   31301
36 infirmière en psychiatrie                              3130   31301
37 registered nurse                                       3130   31301
38 teacher                                                4122      NA
39 registered nurse                                       3130   31301
40 registered practical nurse                             3210   32101
41 truck driver                                           7330   73300
42 registered nurse                                       3130   31301
43 truck driver                                           7330   73300
44 truckdriver                                            7330   73300
45 class 1 driver                                         7330   73300
46 teacher                                                4122      NA
47 doctor                                                 3110   31102
48 truck driver                                           7330   73300
49 teacher catholic                                       4122      NA
50 registered nurse                                       3130   31301</code></pre>
</div>
</div>
</section>
</section>
<section id="ces19-web" class="level3">
<h3 class="anchored" data-anchor-id="ces19-web">CES19 Web</h3>
<p>Next we import the CES 19 data file. Note that there were problems with the encodings of accented characters in the original CES 2019 web file. We devised a fix contained in the R script <code>1_problem_with_encodings.R</code> and execute it here. So, we are working with the original data file provided by CDEM.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>ces19web <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="at">file=</span><span class="fu">here</span>(<span class="st">"Data/CES-E-2019-online_F1.sav"</span>), <span class="at">encoding=</span><span class="st">"latin1"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"1_problem_with_encodings.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The repair is evident in this case:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(pes19_occ_text,<span class="st">"assembleur-m"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cps19_ResponseId, pes19_occ_text)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  cps19_ResponseId  pes19_occ_text      
  &lt;chr&gt;             &lt;chr&gt;               
1 R_2sd9ERBAmYl5dhM assembleur-mécanique</code></pre>
</div>
</div>
<p>Then we convert the variable containing the respondent’s self-reported job title to lower case and then merge again with <code>noc</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pes19_occ_text_lower=</span><span class="fu">str_to_lower</span>(pes19_occ_text)) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(., noc, <span class="fu">join_by</span>(<span class="st">"pes19_occ_text_lower"</span><span class="sc">==</span><span class="st">"title"</span>))<span class="ot">-&gt;</span>ces19web</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note, that in the online surveys CES19 and CES21, respondents were invited to report their job title even if their employment status was something other than having employment. That is to say, people who reported they were retired could also report their job title.</p>
<p>This lead to some confusion. On the one hand, it lead to many cases in the <code>noc</code> file of people saying their positions were <code>retired police officer</code>.</p>
<p>However, many, for whatever reason, did not mention they were retired in their response to the job title question. This information was unavailable to us when we coded the job titles. <em>As a result, many respondents who were not working will have NOC 5- or 4- digit codes. Users should make use of the employment status variable prior to the NOC codes if they want to be sure they are capturing respondents who have paid employment.</em></p>
<p>In the next section we utilize this variable to examine the distribution of employed, retired or respondents in other situations (e.g.&nbsp;students) and their reported occupation titles.</p>
<p>First we recode the employment variable to something useful, matching the categories used above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Recode employment variable</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">employment=</span><span class="fu">case_when</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Anything less than 4 is employed</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    cps19_employment<span class="sc">&lt;</span><span class="dv">4</span> <span class="sc">~</span> <span class="st">"Employed"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">#4 </span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    cps19_employment <span class="sc">==</span><span class="dv">4</span> <span class="sc">~</span> <span class="st">"Retired"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>   cps19_employment <span class="sc">&gt;</span> <span class="dv">8</span> <span class="sc">&amp;</span> cps19_employment<span class="sc">&lt;</span><span class="dv">12</span><span class="sc">~</span> <span class="st">"Employed"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="dv">13</span><span class="sc">==</span>cps19_employment<span class="sc">~</span> <span class="st">"Other"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  ))<span class="ot">-&gt;</span>ces19web</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Show results of recode</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ces19web<span class="sc">$</span>employment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Employed    Other  Retired 
   22675     6139     9008 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Filter in only those who completed the PES</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pes19_consent<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Form groups by employment status</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(employment) <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Select only the two NOC codes</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"NOC"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">my_skim</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(employment, skim_variable, n_missing<span class="sc">:</span>pct_complete) <span class="sc">%&gt;%</span> </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(employment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  employment skim_variable n_missing valid pct_complete
  &lt;chr&gt;      &lt;chr&gt;             &lt;int&gt; &lt;int&gt;        &lt;dbl&gt;
1 Employed   NOC21_4            1492  4208        0.738
2 Employed   NOC21_5            2177  3523        0.618
3 Other      NOC21_4             740   383        0.341
4 Other      NOC21_5             777   346        0.308
5 Retired    NOC21_4             798  2719        0.773
6 Retired    NOC21_5            1254  2263        0.643</code></pre>
</div>
</div>
<p>As a final diagnostic, we print a random sample of the job tiles entered (including some empty responses) and it shows the corresponding NOC21_4 and NOC21_5 codes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pes19_consent<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(employment, pes19_occ_text_lower, NOC21_4, NOC21_5) <span class="sc">%&gt;%</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 4
   employment pes19_occ_text_lower             NOC21_4 NOC21_5
   &lt;chr&gt;      &lt;chr&gt;                              &lt;dbl&gt;   &lt;dbl&gt;
 1 Employed   "financial compliance"              1110   11109
 2 Other      "homemaker"                           NA      NA
 3 Employed   ""                                    NA      NA
 4 Employed   "safety professional"               2112   21120
 5 Employed   ""                                    NA      NA
 6 Employed   "sales and accounts"                6001   60010
 7 Employed   "registered nurse"                  3130   31301
 8 Retired    "meteorology"                       2110   21103
 9 Employed   "welder"                            7210   72106
10 Employed   "coordinator"                       1310      NA
11 Employed   "credit analyst"                    1110   11109
12 Employed   "customer service"                  6440   64409
13 Employed   "enseignement"                      4122      NA
14 Employed   "developer"                           NA      NA
15 Employed   "office worker"                     1410   14100
16 Employed   "clerical in telecommunications"    1410   14100
17 Employed   "insurance"                           NA      NA
18 Other      "cashier"                           6510   65100
19 Retired    "educator"                          4122   41221
20 Employed   "supervisor"                        1002      NA
21 Retired    "life insurance"                    6310   63100
22 Retired    "retraite"                            NA      NA
23 Employed   "pilot"                             7260   72600
24 Employed   ""                                    NA      NA
25 Employed   "customer service"                  6440   64409
26 Retired    "social work"                       4130   41300
27 Employed   "software development"              2123   21232
28 Retired    "telephone worker"                  7220   72204
29 Retired    "sales manager"                     6001   60010
30 Employed   "estimator"                         2230   22303
31 Other      "nurse"                             3130   31301
32 Employed   "broker"                            1110   11103
33 Retired    "cfo"                                  1      12
34 Employed   "underwriter"                       1220   12202
35 Employed   "administrator"                     1310   13100
36 Retired    "director of a patient care"        3130   31300
37 Employed   ""                                    NA      NA
38 Retired    "letter carrier"                    7410   74101
39 Employed   "travel agent"                      6431   64310
40 Other      "customer service rep"              6440   64409
41 Retired    "bank clerk"                        1420   14201
42 Retired    "fonctionnaire"                       NA      NA
43 Employed   "it"                                2122   21222
44 Employed   "non-profit manager"                1001   10019
45 Retired    "vw audi dealership"                6410   64100
46 Employed   "care aide"                         4410   44101
47 Employed   "operator"                            NA      NA
48 Employed   "self employed"                       NA      NA
49 Employed   "journalist"                        5111   51113
50 Employed   "management consultant"             1120   11201</code></pre>
</div>
</div>
<p>This searches for some specific job titles in French and English and returns a random sample of 50 of those entries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: ces19-show-diagnostics-of-specific-titles</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(employment, pes19_occ_text_lower, NOC21_4, NOC21_5) <span class="sc">%&gt;%</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(pes19_occ_text_lower, <span class="st">"carpenter|plumber|driver|nurse|doctor|teacher|electrician"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 4
   employment pes19_occ_text_lower                               NOC21_4 NOC21_5
   &lt;chr&gt;      &lt;chr&gt;                                                &lt;dbl&gt;   &lt;dbl&gt;
 1 Retired    nurse                                                 3130   31301
 2 Retired    teacher                                               4122      NA
 3 Retired    registered nurse                                      3130   31301
 4 Employed   teacher                                               4122      NA
 5 Retired    carpenter                                             7231   72310
 6 Employed   teacher                                               4122      NA
 7 Employed   nurse                                                 3130   31301
 8 Employed   bus driver                                            7330   73301
 9 Retired    registered nurse                                      3130   31301
10 Employed   bus driver                                            7330   73301
11 Retired    teacher                                               4122      NA
12 Employed   carpenter                                             7231   72310
13 Other      special education/resource teacher—i was assaulte…      NA      NA
14 Employed   registered nurse                                      3130   31301
15 Employed   nurse                                                 3130   31301
16 Employed   truck driver                                          7330   73300
17 Retired    teacher                                               4122      NA
18 Employed   teacher                                               4122      NA
19 Retired    teacher                                               4122      NA
20 Retired    teacher                                               4122      NA
21 Other      registered nurse                                      3130   31301
22 Retired    school teacher                                        4122      NA
23 Employed   teacher                                               4122      NA
24 Employed   nurse                                                 3130   31301
25 Employed   teacher                                               4122      NA
26 Retired    teacher                                               4122      NA
27 Employed   truck driver                                          7330   73300
28 Retired    teacher                                               4122      NA
29 Employed   teacher                                               4122      NA
30 Retired    elementary resource teacher                           4122   41221
31 Retired    school teacher                                        4122      NA
32 Employed   registered nurse                                      3130   31301
33 Other      plumber                                               7230   72300
34 Other      nurse                                                 3130   31301
35 Retired    teacher                                               4122      NA
36 Employed   teacher                                               4122      NA
37 Retired    teacher                                               4122      NA
38 Retired    school teacher                                        4122      NA
39 Employed   teacher                                               4122      NA
40 Employed   teacher                                               4122      NA
41 Employed   carpenter                                             7231   72310
42 Employed   teacher                                               4122      NA
43 Employed   electrician                                           7220   72200
44 Employed   teacher                                               4122      NA
45 Retired    school bus driver                                     7330   73301
46 Employed   carpenter                                             7231   72310
47 Retired    teacher                                               4122      NA
48 Retired    teacher                                               4122      NA
49 Employed   teacher                                               4122      NA
50 Retired    driver                                                7520   75200</code></pre>
</div>
</div>
</section>
<section id="ces21-web" class="level3">
<h3 class="anchored" data-anchor-id="ces21-web">CES21 Web</h3>
<section id="import-ces21-web" class="level4">
<h4 class="anchored" data-anchor-id="import-ces21-web">Import CES21 Web</h4>
<p>First, we import the CES21 data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ces21<span class="ot">&lt;-</span><span class="fu">read_sav</span>(<span class="at">file=</span><span class="fu">here</span>(<span class="st">"Data/CES2021tab.sav"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We recreate the <code>employment</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">employment=</span><span class="fu">case_when</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    cps21_employment<span class="sc">&lt;</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Employed"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    cps21_employment<span class="sc">==</span><span class="dv">4</span> <span class="sc">~</span> <span class="st">"Retired"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    cps21_employment <span class="sc">&gt;</span> <span class="dv">8</span> <span class="sc">&amp;</span> cps21_employment<span class="sc">&lt;</span><span class="dv">12</span> <span class="sc">~</span> <span class="st">"Employed"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">'Other'</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  ))<span class="ot">-&gt;</span>ces21</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Show the results</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ces21<span class="sc">$</span>employment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Employed    Other  Retired 
   11659     3177     6132 </code></pre>
</div>
</div>
<p>Then we convert the occupation variable to lower case and merge with <code>noc</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pes21_occ_text_lower=</span><span class="fu">str_to_lower</span>(pes21_occ_text)) <span class="sc">%&gt;%</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(., noc, <span class="fu">join_by</span>(<span class="st">"pes21_occ_text_lower"</span><span class="sc">==</span><span class="st">"title"</span>))<span class="ot">-&gt;</span>ces21</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We filter out only the post-election respondents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Filter in only those who completed the PES</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pes21_consent<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Form groups by employment status</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(employment) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Select only the two NOC codes</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"NOC"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">my_skim</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(employment, skim_variable, n_missing<span class="sc">:</span>pct_complete) <span class="sc">%&gt;%</span> </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(employment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  employment skim_variable n_missing valid pct_complete
  &lt;chr&gt;      &lt;chr&gt;             &lt;int&gt; &lt;int&gt;        &lt;dbl&gt;
1 Employed   NOC21_4            2414  5599        0.699
2 Employed   NOC21_5            3344  4669        0.583
3 Other      NOC21_4            1508   613        0.289
4 Other      NOC21_5            1570   551        0.260
5 Retired    NOC21_4            1175  3760        0.762
6 Retired    NOC21_5            1743  3192        0.647</code></pre>
</div>
</div>
<p>Here we show the same diagnostics as above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pes21_consent<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(employment, pes21_occ_text_lower, NOC21_4, NOC21_5) <span class="sc">%&gt;%</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 4
   employment pes21_occ_text_lower                             NOC21_4 NOC21_5
   &lt;chr&gt;      &lt;chr&gt;                                              &lt;dbl&gt;   &lt;dbl&gt;
 1 Other      &lt;NA&gt;                                                  NA      NA
 2 Retired    retired teacher                                       NA      NA
 3 Retired    consulting                                          1120   11201
 4 Employed   &lt;NA&gt;                                                  NA      NA
 5 Retired    golf superintendent                                 2211   22114
 6 Employed   customer service                                    6440   64409
 7 Retired    retired- former teacher                               NA      NA
 8 Employed   &lt;NA&gt;                                                  NA      NA
 9 Other      &lt;NA&gt;                                                  NA      NA
10 Employed   office administrator                                1311   13110
11 Retired    business analyst consultant                         1120   11201
12 Retired    financial officer                                   1220   12200
13 Employed   clerk                                               1410   14100
14 Retired    gestionnaire                                           1      NA
15 Retired    engineer                                            2130      NA
16 Employed   teacher                                             4122      NA
17 Employed   négociatrice                                        1210   12102
18 Retired    i was an educational assistant                        NA      NA
19 Retired    agriculture                                         8002   80020
20 Employed   account analyst                                     1110   11100
21 Employed   &lt;NA&gt;                                                  NA      NA
22 Other      student                                               NA      NA
23 Employed   public sector                                         NA      NA
24 Retired    clerk                                               1410   14100
25 Employed   assistan gérant dépicerie                           6201   62010
26 Employed   strategic advisor                                   1120   11201
27 Retired    firefighter                                         4210   42101
28 Retired    system analyst                                      2222   22220
29 Employed   full time                                             NA      NA
30 Retired    directeur                                           1001      NA
31 Employed   tech support                                        2222   22221
32 Employed   salarié                                               NA      NA
33 Employed   it                                                  2122   21222
34 Employed   business                                              NA      NA
35 Employed   educator                                            4122   41221
36 Retired    cpa                                                 1110   11100
37 Retired    analyst                                               NA      NA
38 Retired    teacher                                             4122      NA
39 Employed   executive                                              1      NA
40 Employed   businessman                                           NA      NA
41 Employed   curator                                             5110   51101
42 Employed   the performing arts                                 5312   53121
43 Employed   administrative                                      1310   13100
44 Retired    retired                                               NA      NA
45 Retired    technicienne en service de garde milieu scolaire    4310   43100
46 Employed   coordonateur                                        1310      NA
47 Retired    maintainance painter                                7420      NA
48 Employed   operator                                              NA      NA
49 Employed   manager                                             1002   10029
50 Other      administrative assistant                            1311   13110</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: ces21-show-diagnostics-of-specific-titles</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">50</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(employment, pes21_occ_text_lower, NOC21_4, NOC21_5) <span class="sc">%&gt;%</span> </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(pes21_occ_text_lower, <span class="st">"carpenter|plumber|driver|nurse|doctor|teacher|electrician"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 4
   employment pes21_occ_text_lower      NOC21_4 NOC21_5
   &lt;chr&gt;      &lt;chr&gt;                       &lt;dbl&gt;   &lt;dbl&gt;
 1 Employed   nurse                        3130   31301
 2 Other      teacher                      4122      NA
 3 Retired    college teacher              4121   41210
 4 Employed   nurse                        3130   31301
 5 Other      teacher                      4122      NA
 6 Employed   secondary teacher            4122   41220
 7 Employed   plumber                      7230   72300
 8 Retired    artist, ballet teacher       5312   53122
 9 Employed   teacher                      4122      NA
10 Retired    nurse...rpn                  3210   32101
11 Employed   teacher                      4122      NA
12 Employed   electrician                  7220   72200
13 Retired    nurse                        3130   31301
14 Employed   teacher                      4122      NA
15 Employed   esl teacher                  4122      NA
16 Other      disabled, esl teacher        4122   41220
17 Employed   nurse                        3130   31301
18 Retired    truck driver                 7330   73300
19 Employed   nurse                        3130   31301
20 Employed   nurse                        3130   31301
21 Employed   teacher                      4122      NA
22 Employed   teacher                      4122      NA
23 Retired    registered nurse             3130   31301
24 Retired    nurse                        3130   31301
25 Other      nurse                        3130   31301
26 Other      teacher                      4122      NA
27 Retired    teacher                      4122      NA
28 Other      registered nurse             3130   31301
29 Other      licensed practical nurse     3210   32101
30 Retired    retied teacher                 NA      NA
31 Retired    teacher                      4122      NA
32 Retired    teacher                      4122      NA
33 Retired    nurse                        3130   31301
34 Employed   doctor                       3110   31102
35 Employed   teacher                      4122      NA
36 Retired    truck driver                 7330   73300
37 Retired    teacher                      4122      NA
38 Retired    registered nurse  retired      NA      NA
39 Employed   carpenter                    7231   72310
40 Retired    registered nurse             3130   31301
41 Employed   teacher                      4122      NA
42 Retired    registered nurse             3130   31301
43 Retired    nurse                        3130   31301
44 Employed   teacher                      4122      NA
45 Employed   teacher                      4122      NA
46 Employed   teacher                      4122      NA
47 Retired    teacher                      4122      NA
48 Employed   driver                       7520   75200
49 Retired    nurse                        3130   31301
50 Retired    teacher                      4122      NA</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="comprehensive-diagnostics" class="level1">
<h1>Comprehensive Diagnostics</h1>
<p>This section contains a summary table of the diagnostic evaluations conducted separately above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#select pes19 consent variable and NOC</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">consent=</span>pes19_consent, <span class="fu">contains</span>(<span class="st">"NOC"</span>),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>         <span class="co">#Store in object ces19</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>        employment)<span class="ot">-&gt;</span>ces19</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Select ces21 consent variable and NOC variables</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">consent=</span>pes21_consent, <span class="fu">contains</span>(<span class="st">"NOC"</span>),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>         <span class="co">#store in object ces21_2</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>         employment)<span class="ot">-&gt;</span>ces21_2</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Add variables showing which survey they came from </span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>ces19 <span class="sc">%&gt;%</span> </span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Survey=</span><span class="fu">rep</span>(<span class="st">"CES19Web"</span>, <span class="fu">nrow</span>(.)))<span class="ot">-&gt;</span>ces19</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>ces21_2 <span class="sc">%&gt;%</span> </span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Survey=</span><span class="fu">rep</span>(<span class="st">"CES21"</span>, <span class="fu">nrow</span>(.))) <span class="sc">%&gt;%</span> </span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>  <span class="co">#bind ces21-2 to ces19</span></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(ces19) <span class="sc">%&gt;%</span> </span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>  <span class="co">#filter only those rs who participated in PES</span></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(consent<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>  <span class="co">#unselect consent</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>consent) <span class="ot">-&gt;</span>ces19_21</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a><span class="co">#Now prepare ces19phone</span></span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>  ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Filter only those respondents who participated in the post-election-survey</span></span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>        <span class="fu">filter</span>(pc1<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Select only employment and NOC variables</span></span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"NOC"</span>), employment) <span class="sc">%&gt;%</span> </span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Add variable indicated where responses came frpm</span></span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">Survey=</span><span class="fu">rep</span>(<span class="st">"CES19Phone"</span>, <span class="fu">nrow</span>(.))) <span class="sc">%&gt;%</span> </span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>    <span class="co">#bind with ces19-21</span></span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_rows</span>(ces19_21) <span class="sc">%&gt;%</span> </span>
<span id="cb35-35"><a href="#cb35-35" aria-hidden="true" tabindex="-1"></a>    <span class="co">#form groups of survey and employ,ent</span></span>
<span id="cb35-36"><a href="#cb35-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Survey, employment) <span class="sc">%&gt;%</span></span>
<span id="cb35-37"><a href="#cb35-37" aria-hidden="true" tabindex="-1"></a>    <span class="co">#skim to report statistics</span></span>
<span id="cb35-38"><a href="#cb35-38" aria-hidden="true" tabindex="-1"></a>    <span class="fu">my_skim</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb35-39"><a href="#cb35-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Survey, employment, skim_variable, n_missing<span class="sc">:</span>pct_complete) <span class="sc">%&gt;%</span> </span>
<span id="cb35-40"><a href="#cb35-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(Survey, employment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 6
   Survey     employment skim_variable n_missing valid pct_complete
   &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;             &lt;int&gt; &lt;int&gt;        &lt;dbl&gt;
 1 CES19Phone Employed   NOC21_4             360  1467        0.803
 2 CES19Phone Employed   NOC21_5             538  1289        0.706
 3 CES19Phone Other      NOC21_4             285     0        0    
 4 CES19Phone Other      NOC21_5             285     0        0    
 5 CES19Phone Retired    NOC21_4             777     0        0    
 6 CES19Phone Retired    NOC21_5             777     0        0    
 7 CES19Web   Employed   NOC21_4            1492  4208        0.738
 8 CES19Web   Employed   NOC21_5            2177  3523        0.618
 9 CES19Web   Other      NOC21_4             740   383        0.341
10 CES19Web   Other      NOC21_5             777   346        0.308
11 CES19Web   Retired    NOC21_4             798  2719        0.773
12 CES19Web   Retired    NOC21_5            1254  2263        0.643
13 CES21      Employed   NOC21_4            2414  5599        0.699
14 CES21      Employed   NOC21_5            3344  4669        0.583
15 CES21      Other      NOC21_4            1508   613        0.289
16 CES21      Other      NOC21_5            1570   551        0.260
17 CES21      Retired    NOC21_4            1175  3760        0.762
18 CES21      Retired    NOC21_5            1743  3192        0.647</code></pre>
</div>
</div>
<p>It appears that we were much more successful at assigning NOC codes to the web surveys than to the NOC19 phone survey. It’s not entirely clear why that is. To be honest, I would have expected it to be different given that a phone interviewer would have had an opportunity to ensure respondents provided a bit more clear answers.</p>
<p>It is also clear that users should make strong use of the questions on employment status in combination with the NOC codes in the web surveys as respondents who were not employed often provided job titles, presumably from their past primary occupations. It’s not hard to imagine how one might want to make use of such information, but it would be very specific use cases.</p>
</section>
<section id="export-of-data-files" class="level1">
<h1>Export of data files</h1>
<p>Finally, we export the CES data files separately to provide to CDEM to disseminate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Export Ces19phone Stata</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_dta</span>(<span class="at">path=</span><span class="fu">here</span>(<span class="st">"Data/ces2019_phone_noc.dta"</span>))</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Export Ces19phone Rdata</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">save</span>(<span class="at">file=</span><span class="fu">here</span>(<span class="st">"Data/ces2019_phone_noc.rdata"</span>))</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Export CES19phone SPSS</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>ces19phone <span class="sc">%&gt;%</span> </span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_sav</span>(<span class="at">path=</span><span class="fu">here</span>(<span class="st">"Data/ces2019_phone_noc.sav"</span>))</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Export Ces19web Stata</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_dta</span>(<span class="at">path=</span><span class="fu">here</span>(<span class="st">"Data/ces2019_web_noc.dta"</span>))</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Export Ces19phone Rdata</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">save</span>(<span class="at">file=</span><span class="fu">here</span>(<span class="st">"Data/ces2019_web_noc.rdata"</span>))</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Export CES19web SPSS</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>ces19web <span class="sc">%&gt;%</span> </span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_sav</span>(<span class="at">path=</span><span class="fu">here</span>(<span class="st">"Data/ces2019_web_noc.sav"</span>))</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Export Ces21 Stata</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_dta</span>(<span class="at">path=</span><span class="fu">here</span>(<span class="st">"Data/ces2021_noc.dta"</span>))</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a><span class="co">#Export CES21 Rdata</span></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">save</span>(<span class="at">file=</span><span class="fu">here</span>(<span class="st">"Data/ces2021_noc.rdata"</span>))</span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a><span class="co">#Export CES21 SPSS</span></span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>ces21 <span class="sc">%&gt;%</span> </span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_sav</span>(<span class="at">path=</span><span class="fu">here</span>(<span class="st">"Data/ces2021_noc.sav"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>